print "Building engine"

CC = 'g++'
CCFLAGS = '-O3 -Wall -c -fmessage-length=0 -fPIC -MMD -MP'
LIBS = '-lmylib'
LIBPATH = '../mylib/'
LINKFLAGS = ''

CPPPATH = './include ../mylib/include'
SOURCE = '\
	./source/hq_engine.cpp\
	./source/linux_hq_window.cpp\
	./source/mesh/hq_meshbase.cpp\
	./source/mesh/hq_staticmesh.cpp\
	./source/rendersystem/linux_hq_rendersystem.cpp\
	./source/resource/hq_meshmanager.cpp\
	./source/scene/hq_scenenode.cpp\
'

SharedLibrary('hqengine', Split(SOURCE),\
	CPPPATH = Split(CPPPATH),\
	LIBS = Split(LIBS),\
	LIBPATH = Split(LIBPATH),\
	CCFLAGS = Split(CCFLAGS),\
	LINKFLAGS = Split(LINKFLAGS),\
)
